apiVersion: v1
kind: Pod
metadata:
 name: podman-rootless
spec:
 containers:
   - name: rootless
     image: 'image-registry.openshift-image-registry.svc:5000/podman/podman-builder:latest'
     args:
       - sleep
       - "1000000"
     securityContext:
       privileged: true
       runAsUser: 1000
